/**
 * VS Code API Types
 * 
 * This barrel file exports all type definitions for the VS Code API.
 * Types are organized by category for better maintainability.
 */

// Core types
export type {
  Disposable,
  Event,
  ProviderResult,
  Thenable
} from './core';

// Document and editor types
export type {
  TextDocument,
  TextEditor,
  TextEditorEdit,
  TextEditorOptions,
  TextEditorDecorationType,
  TextEditorSelectionChangeEvent,
  TextEditorOptionsChangeEvent,
  TextEditorViewColumnChangeEvent,
  TextEditorVisibleRangesChangeEvent,
  TextLine,
  EndOfLineSequence,
  TextDocumentWillSaveEvent,
  TextDocumentChangeEvent,
  TextDocumentContentChangeEvent,
  TextDocumentShowOptions,
  DecorationOptions,
  DecorationRenderOptions,
  ThemableDecorationRenderOptions,
  ThemableDecorationAttachmentRenderOptions,
  ThemableDecorationInstanceRenderOptions
} from './editor';

// Workspace types
export type {
  WorkspaceFolder,
  WorkspaceFoldersChangeEvent,
  WorkspaceConfiguration,
  ConfigurationChangeEvent,
  FileSystemWatcher,
  FileCreateEvent,
  FileDeleteEvent,
  FileRenameEvent,
  FileWillCreateEvent,
  FileWillDeleteEvent,
  FileWillRenameEvent,
  FileStat,
  FileSystem,
  FileSystemError,
  FileChangeEvent,
  FileChangeType,
  GlobPattern,
  RelativePattern,
  DocumentFilter,
  DocumentSelector,
  TextSearchQuery,
  TextSearchOptions,
  TextSearchResult,
  TextSearchMatch,
  TextSearchComplete,
  FileSearchQuery,
  FileSearchOptions,
  FileSearchProvider,
  TextSearchProvider,
  SearchOptions,
  FindTextInFilesOptions,
  WorkspaceEdit,
  WorkspaceEditEntryMetadata,
  TextEdit,
  SnippetTextEdit,
  NotebookEdit,
  ResourceTextEdit,
  ResourceFileEdit
} from './workspace';

// Language types
export type {
  CompletionItem,
  CompletionList,
  CompletionContext,
  CompletionItemProvider,
  CompletionItemLabel,
  CompletionItemTag,
  InlineCompletionItem,
  InlineCompletionList,
  InlineCompletionContext,
  InlineCompletionItemProvider,
  InlineCompletionTriggerKind,
  ParameterInformation,
  SignatureInformation,
  SignatureHelp,
  SignatureHelpContext,
  SignatureHelpProvider,
  SignatureHelpProviderMetadata,
  Hover,
  HoverProvider,
  EvaluatableExpression,
  EvaluatableExpressionProvider,
  InlineValue,
  InlineValueContext,
  InlineValueProvider,
  InlineValueText,
  InlineValueVariableLookup,
  InlineValueEvaluatableExpression,
  DocumentHighlight,
  DocumentHighlightProvider,
  DocumentSymbol,
  DocumentSymbolProvider,
  DocumentSymbolProviderMetadata,
  SymbolInformation,
  WorkspaceSymbolProvider,
  ReferenceContext,
  ReferenceProvider,
  RenameProvider,
  PrepareRenameResult,
  SemanticTokens,
  SemanticTokensBuilder,
  SemanticTokensLegend,
  SemanticTokensProvider,
  SemanticTokensEdits,
  SemanticTokensEdit,
  DocumentSemanticTokensProvider,
  DocumentRangeSemanticTokensProvider,
  DefinitionProvider,
  Definition,
  DefinitionLink,
  DeclarationProvider,
  Declaration,
  ImplementationProvider,
  TypeDefinitionProvider,
  TypeHierarchyProvider,
  TypeHierarchyItem,
  CallHierarchyProvider,
  CallHierarchyItem,
  CallHierarchyIncomingCall,
  CallHierarchyOutgoingCall,
  LinkedEditingRangeProvider,
  LinkedEditingRanges,
  SelectionRange,
  SelectionRangeProvider,
  FoldingRange,
  FoldingRangeProvider,
  FoldingContext,
  DocumentColorProvider,
  Color,
  ColorInformation,
  ColorPresentation,
  DocumentLinkProvider,
  DocumentLink,
  CodeLens,
  CodeLensProvider,
  CodeAction,
  CodeActionProvider,
  CodeActionProviderMetadata,
  CodeActionContext,
  DocumentFormattingEditProvider,
  DocumentRangeFormattingEditProvider,
  OnTypeFormattingEditProvider,
  FormattingOptions,
  Diagnostic,
  DiagnosticRelatedInformation,
  DiagnosticCollection,
  DiagnosticChangeEvent,
  DocumentDropEditProvider,
  DocumentDropEdit,
  DataTransfer,
  DataTransferItem,
  DataTransferFile,
  DocumentPasteEditProvider,
  DocumentPasteEdit,
  InlayHint,
  InlayHintLabelPart,
  InlayHintProvider
} from './language';

// Window types
export type {
  TextEditorSelectionChangeKind,
  TextEditorRevealType,
  TextEditorLineNumbersStyle,
  TextEditorCursorStyle,
  StatusBarItem,
  StatusBarAlignment,
  Terminal,
  TerminalOptions,
  TerminalExitStatus,
  TerminalDimensions,
  TerminalProfile,
  TerminalProfileProvider,
  TerminalLink,
  TerminalLinkContext,
  TerminalLinkProvider,
  ExtensionTerminalOptions,
  Pseudoterminal,
  CustomExecution,
  ShellExecution,
  ProcessExecution,
  TaskExecution,
  OutputChannel,
  LogOutputChannel,
  MessageItem,
  MessageOptions,
  InputBoxOptions,
  InputBoxValidationMessage,
  QuickPickItem,
  QuickPickOptions,
  QuickPickItemButtonEvent,
  QuickPickItemButton,
  QuickPick,
  QuickInputButton,
  QuickInputButtons,
  OpenDialogOptions,
  SaveDialogOptions,
  ProgressOptions,
  Progress,
  TreeView,
  TreeViewOptions,
  TreeViewExpansionEvent,
  TreeViewSelectionChangeEvent,
  TreeViewVisibilityChangeEvent,
  TreeDataProvider,
  TreeItem,
  TreeItemLabel,
  TreeItemCheckboxState,
  TreeCheckboxChangeEvent,
  WebviewView,
  WebviewViewProvider,
  WebviewViewResolveContext,
  WebviewPanel,
  WebviewPanelOptions,
  WebviewOptions,
  WebviewPortMapping,
  Webview,
  WebviewPanelSerializer,
  CustomDocument,
  CustomDocumentBackup,
  CustomDocumentBackupContext,
  CustomDocumentContentChangeEvent,
  CustomDocumentEditEvent,
  CustomDocumentOpenContext,
  CustomReadonlyEditorProvider,
  CustomEditorProvider,
  CustomTextEditorProvider,
  TabGroups,
  TabGroup,
  Tab,
  TabInputText,
  TabInputTextDiff,
  TabInputCustom,
  TabInputNotebook,
  TabInputNotebookDiff,
  TabInputTerminal,
  TabInputWebview
} from './window';

// Command types
export type {
  Command,
  CommandSignature
} from './commands';

// Extension types
export type {
  Extension,
  ExtensionContext,
  ExtensionMode,
  ExtensionKind,
  Memento,
  SecretStorage,
  SecretStorageChangeEvent,
  EnvironmentVariableCollection,
  EnvironmentVariableMutator,
  EnvironmentVariableScope,
  GlobalEnvironmentVariableCollection
} from './extensions';

// Debug types
export type {
  DebugSession,
  DebugSessionCustomEvent,
  DebugSessionOptions,
  DebugConfiguration,
  DebugConfigurationProvider,
  DebugConfigurationProviderTriggerKind,
  DebugAdapterDescriptor,
  DebugAdapterDescriptorFactory,
  DebugAdapterExecutable,
  DebugAdapterExecutableOptions,
  DebugAdapterServer,
  DebugAdapterNamedPipeServer,
  DebugAdapterInlineImplementation,
  DebugAdapterTracker,
  DebugAdapterTrackerFactory,
  DebugConsole,
  Breakpoint,
  SourceBreakpoint,
  FunctionBreakpoint,
  DataBreakpoint,
  BreakpointsChangeEvent,
  DebugProtocolBreakpoint,
  DebugProtocolSource,
  DebugProtocolMessage,
  DebugThread,
  DebugStackFrame,
  DebugVariable,
  DebugVisualization,
  DebugVisualizationProvider,
  DebugVisualizationContext,
  InlineDebugAdapter,
  InlineDebugAdapterProvider
} from './debug';

// Task types
export type {
  Task,
  TaskDefinition,
  TaskScope,
  TaskProvider,
  TaskExecution,
  TaskProcessStartEvent,
  TaskProcessEndEvent,
  TaskFilter,
  TaskPresentationOptions,
  TaskRevealKind,
  TaskPanelKind,
  TaskGroup,
  ProcessExecutionOptions,
  ShellExecutionOptions,
  ShellQuotingOptions,
  ShellQuoting,
  RunOptions
} from './tasks';

// SCM types
export type {
  SourceControl,
  SourceControlInputBox,
  SourceControlResourceGroup,
  SourceControlResourceState,
  SourceControlResourceDecorations,
  SourceControlHistoryProvider,
  SourceControlHistoryOptions,
  SourceControlHistoryItem,
  SourceControlHistoryItemRef,
  SourceControlHistoryItemChange,
  SourceControlHistoryItemStatistics,
  SourceControlCommitTemplate
} from './scm';

// Comment types
export type {
  CommentController,
  CommentOptions,
  CommentThread,
  CommentThreadState,
  CommentThreadCollapsibleState,
  Comment,
  CommentAuthorInformation,
  CommentMode,
  CommentReaction,
  CommentingRangeProvider,
  CommentRule,
  CommentThreadTemplate,
  CommentReply
} from './comments';

// Authentication types
export type {
  AuthenticationSession,
  AuthenticationSessionAccountInformation,
  AuthenticationGetSessionOptions,
  AuthenticationProvider,
  AuthenticationProviderInformation,
  AuthenticationSessionsChangeEvent,
  AuthenticationProviderAuthenticationSessionsChangeEvent
} from './authentication';

// Test types
export type {
  TestController,
  TestItem,
  TestItemCollection,
  TestRun,
  TestRunProfile,
  TestRunProfileKind,
  TestRunRequest,
  TestMessage,
  TestMessageStackFrame,
  TestTag,
  TestCoverage,
  FileCoverage,
  StatementCoverage,
  BranchCoverage,
  FunctionCoverage,
  TestSnapshot,
  TestSnapshotDifference
} from './tests';

// Notebook types
export type {
  NotebookController,
  NotebookControllerAffinity,
  NotebookDocument,
  NotebookCell,
  NotebookCellKind,
  NotebookCellOutput,
  NotebookCellOutputItem,
  NotebookCellData,
  NotebookData,
  NotebookCellExecution,
  NotebookCellExecutionSummary,
  NotebookCellStatusBarItem,
  NotebookCellStatusBarItemProvider,
  NotebookCellStatusBarAlignment,
  NotebookEditor,
  NotebookEditorRevealType,
  NotebookEditorSelectionChangeEvent,
  NotebookEditorVisibleRangesChangeEvent,
  NotebookRange,
  NotebookDocumentContentOptions,
  NotebookDocumentContentProvider,
  NotebookSerializer,
  NotebookKernelSourceAction,
  NotebookRendererScript,
  NotebookCellExecutionState,
  NotebookCellExecutionStateChangeEvent,
  NotebookDocumentCellChange,
  NotebookDocumentContentChange,
  NotebookDocumentChangeEvent,
  NotebookEdit,
  NotebookEditorEdit,
  NotebookDocumentShowOptions,
  NotebookCellMetadataChangeEvent,
  NotebookCellOutputsChangeEvent,
  NotebookCellLanguageChangeEvent,
  NotebookDocumentMetadataChangeEvent,
  NotebookDocumentCellExecutionStateChangeEvent,
  NotebookRenderRequest
} from './notebooks';

// Miscellaneous types
export type {
  AccessibilityInformation,
  CancellationToken,
  CancellationTokenSource,
  CharacterPair,
  Clipboard,
  CommentingRanges,
  ConfigurationScope,
  CustomDocumentBackupEditContext,
  CustomDocumentEditOperation,
  DataTransferItemAsString,
  DebugAdapterTrackerSession,
  DebugSessionNamedPipeServer,
  DebugVisualizationTree,
  DebugVisualizationTreeItem,
  DeclarationLink,
  DefinitionProvider2,
  DocumentDropEditProviderMetadata,
  EnterAction,
  ExtensionTerminalProfile,
  ExternalUriOpener,
  FileOperationFilter,
  FileOperationPattern,
  FileOperationPatternKind,
  FileOperationProviderMetadata,
  FileSearchProviderNew,
  HierarchyItem,
  IframeEditorContentOptions,
  ImplementationLink,
  InlineCompletionsAdditions,
  InsertReplaceEdit,
  InteractiveWindowInput,
  LanguageConfiguration,
  LanguageModelChat,
  LanguageModelChatFunction,
  LanguageModelChatFunctionCall,
  LanguageModelChatFunctionResult,
  LanguageModelChatMessage,
  LanguageModelChatMessageRole,
  LanguageModelChatOptions,
  LanguageModelChatResponse,
  LanguageModelChatTool,
  LanguageModelError,
  LanguageModelFunctionInformation,
  LanguageModelPrompt,
  LanguageModelPromptTsxPart,
  LanguageModelSystem,
  LanguageModelSystemOptions,
  LanguageModelToolCallOptions,
  LanguageModelToolChoice,
  LanguageModelToolInformation,
  LanguageModelToolResult,
  LogLevel,
  MultiDocumentHighlight,
  NotebookCellExecutionTask,
  NotebookCellStatusItem,
  NotebookDocumentBackup,
  OnEnterRule,
  PartialAcceptInfo,
  PartialAcceptTriggerKind,
  PortAutoForwardAction,
  PortAttributes,
  PortAttributesProvider,
  PortAutoForwardActionResult,
  ProfileContentHandler,
  RemoteAuthorityResolver,
  RemoteConnectionData,
  ResolvedAuthority,
  ShareableItem,
  ShareProvider,
  SourceControlHistoryQuery,
  SourceControlMultiDiffEditor,
  SourceControlResourceThemableDecorations,
  TabChangeEvent,
  TabGroupChangeEvent,
  TabInputChat,
  TabInputInteractiveWindow,
  TabInputMultiDiff,
  TelemetryLogger,
  TelemetryLoggerOptions,
  TelemetrySender,
  TerminalEditorLocationOptions,
  TerminalOutputAnchor,
  TerminalOutputLink,
  TerminalQuickFixCommandEvent,
  TerminalQuickFixProvider,
  TerminalQuickFixTerminalCommand,
  TerminalShellExecutionEndEvent,
  TerminalShellExecutionStartEvent,
  TerminalShellIntegration,
  TerminalShellIntegrationChangeEvent,
  TerminalSplitLocationOptions,
  TestCoverageProfile,
  TestItemRequest,
  TestObserver,
  TestResultSnapshot,
  TestRunProfileHandler,
  TestRunSnapshot,
  TestingCoverageBarRenderOptions,
  TextDocumentContentProvider,
  TextDocumentSaveReason,
  TextDocumentShowOptions as TextDocumentShowOptionsNew,
  TextEditorVisibleRangesChangeKind,
  TextSearchCompleteNew,
  TextSearchContextNew,
  TextSearchMatchNew,
  TextSearchProviderNew,
  TextSearchQueryNew,
  TextSearchResultNew,
  TimelineChangeEvent,
  TimelineItem,
  TimelineOptions,
  TimelineProvider,
  TypeDefinitionLink,
  TypeHierarchyPrepareResult,
  UriHandler,
  UriOpenOptions,
  WebviewEditorDropData,
  WorkspaceEditMetadata,
  WorkspaceFileEditOptions,
  WorkspaceFileOperationOptions,
  WorkspaceFileOperationsEvent,
  WorkspaceFileTextEdit,
  WorkspaceSymbol,
  WorkspaceTextEdit,
  WorkspaceWillSaveTextDocumentEvent
} from './misc';

// Re-export specific classes that are used as types
export { Position, Range, Selection, Location } from './position';
export { Uri } from '../Uri';
export { EventEmitter } from '../EventEmitter';
export { ThemeColor, ThemeIcon } from './theme';
export { MarkdownString } from './markdown';
export { SnippetString } from './snippet';